config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :boxes
  resources :components
  resources :rules

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/box.rb
class Box < ApplicationRecord
    belongs_to :game
    has_one_attached :image

    validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: %i[ show edit update destroy ]

  # GET /boxes or /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1 or /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes or /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: "Box was successfully created." }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1 or /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: "Box was successfully updated." }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1 or /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: "Box was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def box_params
      params.require(:box).permit(:content, :game_id, :image)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_with(model: @box, local: true) do |form| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<div class="container">
    <h1>Editing Box</h1>

    <%= render 'form', box: @box %>

    <%= link_to 'Show', @box %> |
    <%= link_to 'Back', boxes_path %>
</div>

app/views/boxes/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Boxes</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @boxes.each do |box| %>
        <tr>
          <td><%= image_tag box.image.variant(resize: "100x100", colorspace: "gray") %></td>
          <td><%= link_to 'See better', rails_blob_path(box.image, disposition: "preview") %></td>
          <td><%= link_to 'Download', rails_blob_path(box.image, disposition: "attachment") %></td>
          <td><%= box.content %></td>
          <td><%= link_to 'Show', box %></td>
          <td><%= link_to 'Edit', edit_box_path(box) %></td>
          <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Box', new_box_path %>

</div>

app/views/boxes/new.html.erb
<div class="container">
    <h1>New Box</h1>

    <%= render 'form', box: @box %>

    <%= link_to 'Back', boxes_path %>
</div>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @box.content %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>