config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :boxes
  resources :components
  resources :rules

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :rule, dependent: :destroy
  has_many :components, dependent: :destroy
  has_one :box, dependent: :destroy

  enum typecomp: %w[piece part]

  accepts_nested_attributes_for :rule, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :components, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :box, reject_if: :all_blank, allow_destroy: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  # Calling set_select for the enum of typecomp
  before_action :set_select, only: %i[ new edit create update ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    @box = Box.new
    @rule = Rule.new
    @component = Component.new
    @game.build_box
    @game.build_rule
    @game.components.build
  end

  # GET /games/1/edit
  def edit
    @box = Box.new
    @rule = Rule.new
    @component = Component.new
    @game.build_box
    @game.build_rule
    @game.components.build
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Selec for the enum of typescomp in the form
    def set_select
      @typecomps = Component.typecomps.keys.to_a
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:title, :description, { rule_attributes: [:id, :name, :content, :document, :_destroy] }, { components_attributes: [:id, :name, :typecomp, {images: []}, :_destroy] }, { box_attributes: [:id, :content, :image, :_destroy] } )
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_box_fields.html.erb
<div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
</div>

app/views/games/_component_fields.html.erb
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :typecomp %>
    <%= f.select :typecomp, @typecomps, class: "form-control"  %>
</div>

<div class="form-group">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true, class: "form-control"  %>
</div>

app/views/games/_form.html.erb
<%= form_with(model: @game, local: true) do |form| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.fields_for :box do |ff| %>
      <%= render 'box_fields', f: ff %>
    <% end %>
  </div>

  <div class="field">
    <%= link_to_add_association 'Add box', form, :box, force_non_association_create: true %>
  </div>

  <div class="field">
    <%= form.fields_for :rule do |ff| %>
      <%= render 'rule_fields', f: ff %>
    <% end %>
  </div>

  <div class="field">
    <%= link_to_add_association 'Add rule', form, :rule, force_non_association_create: true %>
  </div>

  <div class="field">
    <%= form.fields_for :components do |ff| %>
      <%= render 'component_fields', f: ff %>
    <% end %>
  </div>

  <div class="field">
    <%= link_to_add_association 'Add component', form, :components %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_rule_fields.html.erb
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control"  %>
</div>

<div class="form-group">
    <%= f.label :document %>
    <%= f.file_field :document, class: "form-control"  %>
</div

app/views/games/edit.html.erb
<div class="container">
    <h1>Editing Game</h1>

    <%= render 'form', game: @game %>

    <%= link_to 'Show', @game %> |
    <%= link_to 'Back', games_path %>
</div>

app/views/games/index.html.erb
<div id="main">

  <div class="container">

    <p id="notice"><%= notice %></p>

    <div class="container pt-5">
      <h1>Register a new game</h1>
      <%= link_to 'Add', new_game_path, class: "btn btn-light" %> 
    </div>

    <div class="container text-right pb-5">
      <h3>More details</h3>
      <%= link_to 'Boxes', boxes_path %> 
      <%= link_to 'Rules', rules_path %> 
      <%= link_to 'Part & Pieces', components_path %> 
    </div>

    <% @games.each do |game| %>
      <div class="card">
        <h1 class="card-header"><%= game.title %></h1>
        <div class="card-body">
          <div class="container text-right">
            <!-- <%# link_to game do %><i class="far fa-eye fa-2x"></i><%# end %> -->
            <%= link_to edit_game_path(game) do %><i class="far fa-edit fa-2x"></i><% end %>
            <%= link_to game, method: :delete, data: { confirm: 'Are you sure?' } do %><i class="far fa-trash-alt fa-2x"></i><% end %></td>  
          </div>
          <h2 class="card-title">Description</h2>
            <p class="card-text"><%= game.description%></p>
            <div class="container">

              <div class="container py-3">
              <h2>Box content</h2>
                <div class="row">
                  <div class="col text-center">
                    <%= image_tag game.box.image.variant(resize: "100x100", colorspace: "gray") %>
                  </div>
                  <div class="col">
                    <p><%= game.box.content %> </p>
                    <%= link_to rails_blob_path(game.box.image, disposition: "attachment") do %><i class="fas fa-download fa-2x"></i><% end %> <p>Box</p>
                  </div>
                </div>
              
                <div class="container py-3">
                  <h2 class="py-2">The Rules of <%="#{game.title}"%></h2>
                  <p>Name of the manual: <%= game.rule.name %></p>
                  <h4>About the Rules</h4>
                    <p><%= game.rule.content %></p>
                  <h4>How to play?</h4>
                    <%# link_to 'See', rails_blob_path(game.rule.document, disposition: "preview") %>
                    <%= link_to "Manual #{game.title}", rails_blob_path(game.rule.document, disposition: "attachment") %>
                </div>
                
                <div class="container py-3">
                  <h2 class="pb-3">Part & Pieces of <%="#{game.title}"%></h2>
                  <% game.components.each do |component| %>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <h4>Type <%= component.typecomp %>: <%= component.name %></h4>
                      </div>
                      <div class="col">
                        <% component.images.each do |c| %>
                          <ul>
                            <li>
                              <%# image_tag c.variant(resize: "100x100", colorspace: "gray") %>
                              <%= link_to rails_blob_path(c, disposition: "preview") do %><i class="far fa-eye fa-2x"></i><% end %>
                            </li>
                          </ul>
                        <% end %>
                        </div>
                      <div class="col">
                      <% component.images.each do |c| %>
                        <ul>
                          <li>
                            <%= link_to rails_blob_path(c, disposition: "attachment") do %><i class="fas fa-download fa-2x"></i><% end %> <%= "#{component.name}" %>
                          </li>
                        </ul>
                      <% end %>
                      </div>

                    </div>
                  </div>
                  <% end %>
                </div>
              
            </div>
        </div>
      </div>
      <div class="card-footer text-muted text-center"><%= game.created_at.strftime("%Y-%m-%d") %> (<%= time_ago_in_words(game.created_at) %>)</div>
    <% end %>

  </div>           

</div>

app/views/games/new.html.erb
<div class="container">
    <h1>New Game</h1>

    <%= render 'form', game: @game %>

    <%= link_to 'Back', games_path %>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @game.rule %>
</p>

<p>
  <strong>Component:</strong>
  <%= @game.components %>
</p>

<p>
  <strong>Box:</strong>
  <%= @game.box %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>