config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :boxes
  resources :components
  resources :rules

  root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rule.rb
class Rule < ApplicationRecord
    belongs_to :game
    has_one_attached :document

    validates :document, presence: true, blob: { content_type: ['application/pdf'], size_range: 1..5.megabytes }
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: %i[ show edit update destroy ]

  # GET /rules or /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1 or /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules or /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: "Rule was successfully created." }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1 or /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: "Rule was successfully updated." }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1 or /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: "Rule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rule_params
      params.require(:rule).permit(:name, :content, :game_id, :document)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<%= form_with(model: @rule, local: true) do |form| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :document %>
    <%= form.file_field :document, class: "form-control"  %>
  </div

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<div class="container">
    <h1>Editing Rule</h1>

    <%= render 'form', rule: @rule %>

    <%= link_to 'Show', @rule %> |
    <%= link_to 'Back', rules_path %>
</div>

app/views/rules/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Rules</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Content</th>
        <th>Document</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @rules.each do |rule| %>
        <tr>
          <td><%= rule.name %></td>
          <td><%= rule.content %></td>
          <td><%= image_tag rule.document, size: "100x100" %></td>
          <td><%= link_to 'See better', rails_blob_path(rule.document, disposition: "preview") %></td>
          <td><%= link_to 'Download', rails_blob_path(rule.document, disposition: "attachment") %></td>

          <td><%= link_to 'Show', rule %></td>
          <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
          <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Rule', new_rule_path %>

</div>

app/views/rules/new.html.erb
<div class="container">
    <h1>New Rule</h1>

    <%= render 'form', rule: @rule %>
    
    <%= link_to 'Back', rules_path %>    
</div>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @rule.content %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>